#!/bin/bash
pink="\e[0;35m"
echo -e "
                   ▄█▀▀▀       ▀▀▀█▄
                 ▄███▄▄  ▀▄██▄▀  ▄▄███▄
                 ▀██▄▄▄▄████████▄▄▄▄██▀
                   ▄▄▄▄██████████▄▄▄▄
                  ▐▐▀▐▀ ▀██████▀ ▀▌▀▌▌" | lolcat

echo ""
echo -e "     $pink                   mr rahim             "
echo ""
echo ""
